#!/usr/bin/env perl
require 5.008;
BEGIN { $^W = 1; }
use strict;

my $whoami = ($0 =~ m,([^/\\]*)$,) ? $1 : $0;
#my $dirname = ($0 =~ m,(.*)[/\\][^/\\]+$,) ? $1 : ".";

my $out = undef;
my $c = 0;
while (@ARGV)
{
    my $arg = shift(@ARGV);
    if ($arg eq '-o')
    {
	if (@ARGV)
	{
	    $out = shift(@ARGV);
	}
    }
    elsif ($arg eq '-c')
    {
	$c = 1;
    }
    elsif ($arg =~ m/(.*)\.c(c|pp)?$/)
    {
	if (! defined $out)
	{
	    $out = "$1.o";
	}
    }
}
$out = 'a.out' unless defined $out;
open(O, ">$out");
print O "#out\n";
close(O);
