#!/usr/bin/env perl
BEGIN { $^W = 1; }
use strict;

if (! ((exists $ENV{'NO_QCC'}) && ($ENV{'NO_QCC'} eq '1')))
{
    print "native-compiler qcc.release\n";
    print "native-compiler qcc.debug\n";
    print "native-compiler qcc\n";
}
