#!/usr/bin/env perl
#
# This script provides platform data for object-code platform types.
#

require 5.008;
BEGIN { $^W = 1; }
use strict;

my $whoami = ($0 =~ m,([^/\\]*)$,) ? $1 : $0;
#my $dirname = ($0 =~ m,(.*)[/\\][^/\\]+$,) ? $1 : ".";

# object-code platforms are os.cpu.toolset.compiler.

my $windows = 0;
if ((@ARGV == 1) && ($ARGV[0] eq '--windows'))
{
    $windows = 1;
}

my @compilers = ();
if ($windows)
{
    # XXX Need a better way to know whether to get mingw.  If this is
    # cygwin and some appropriate API header file and gcc binary
    # exist, and if NO_MINGW is not set, then enable mingw.  Make sure
    # we set NO_MINGW in the test suite if we have msvc so we don't
    # get more platforms in the output which would cause test suite
    # failures.
    if ((exists $ENV{'MINGW'}) && ($ENV{'MINGW'} eq '1'))
    {
	push(@compilers, 'mingw.release');
	push(@compilers, 'mingw.debug');
	push(@compilers, 'mingw');
    }
    if (exists $ENV{'VCINSTALLDIR'})
    {
	push(@compilers, 'msvc.release');
	push(@compilers, 'msvc.debug');
	push(@compilers, 'msvc');
    }
}
else
{
    push(@compilers, 'gcc.release');
    push(@compilers, 'gcc.debug');
    push(@compilers, 'gcc');
}

foreach my $c (@compilers)
{
    print "native-compiler $c\n";
}
