#!/usr/bin/env perl

require 5.008;
BEGIN { $^W = 1; }
use strict;

foreach my $o (".release", ".debug", "")
{
    print "platform os.cpu.toolset.echo$o -type echo\n";
}
print "platform -lowpri os.cpu.toolset.echo.lowpri -type echo\n";
